### ISSUE TITLE
completion points' numbers

### ISSUE THREAD

**Issue by JCPRO2021** [junzhezhang/shape-inversion#10]
completion points' numbers can be changed?

**Comment by junzhezhang** [comment]
Hi, the input resolution is flexible, while the complete shape resolution is fixed at 2048, as the network is MLP with final layer of 2048 nodes. Here, resolution refers to number of points in the point cloud. Hope it explains.

**Comment by JCPRO2021** [comment]
Thanks for your kind reponse. I am a beginner in DL and pointcloud completion .I want to ask two questions:

First, I see the complete_pcds in test_data.h5 at a fixed number of 2048, and incomplete_pcds is the same number. can that  be changed by changing the network? or directly input any numbers of complete and partial points without simplification. You know some big stuffs are more than 2048 points.

Secondly, it is possible for me to change nodes of MLP in final layer depend on the lacking area and points density to increase the output numbers of points ?

Looking forward to your kind reponse！

**Comment by junzhezhang** [comment]
@JCPRO2021 you can change the network architecture for sure, but increasing it to a significant large number might be difficult to converge. Alternatively, you can downsample the data.

**Comment by JCPRO2021** [comment]
Thank you for your kind help. 
(1) During pre_train process, the batch_size is too large, in my computer, 25 is the maximun. So how can I do to imporve the training? Increasing the number of epoch? 
(2) How can determine the best epoch number?
(3) In addition, the format of my own dataset is pcd (or ply). So if I need to convert them into h5py formt?

Looking forward to your reply.
