### ISSUE TITLE
CUDA out of memory when evaluating result

### ISSUE THREAD

**Issue by satoko5793** [junzhezhang/shape-inversion#12]
Hi, I've successfully run the training process, but encountered a problem during evaluation. I'm not sure if it is just because I don't have a large nough GPU. Here is the Traceback:
(shapeinversion) xieyuqiu@SYS-4029GP-TRT:~/shape-inversion$ python eval_completion.py --eval_with_GT true --saved_results_path saved_results/CRN_chair
Traceback (most recent call last):
  File "eval_completion.py", line 202, in <module>
    eval_completion_with_gt(args.saved_results_path)
  File "eval_completion.py", line 160, in eval_completion_with_gt
    cd_ls, acc_ls, comp_ls, f1_ls = compute_4_metrics(ours_gt, ours_output)
  File "eval_completion.py", line 56, in compute_4_metrics
    dist1, dist2 , _, _ = distChamfer(pcn_gt, pcn_output)
  File "/data2/xieyuqiu/shape-inversion/external/ChamferDistancePytorch/chamfer_python.py", line 35, in distChamfer
    zz = torch.bmm(x, y.transpose(2, 1))
RuntimeError: CUDA out of memory. Tried to allocate 4.69 GiB (GPU 0; 11.77 GiB total capacity; 29.38 MiB already allocated; 3.85 GiB free; 40.00 MiB reserved in total by PyTorch)

**Comment by junzhezhang** [comment]
Yes, perhaps you need to play with the evaluation functions to reduce the GRAM footprint.

**Comment by satoko5793** [comment]
Solved，
I changed eval_completion.py line56 in compute_4_metrics(pcn_gt, pcn_output):
dist1, dist2 , _, _ = distChamfer(pcn_gt, pcn_output) -> dist1, dist2 , _, _ = distChamfer(pcn_gt.cpu(), pcn_output.cpu())
