### ISSUE TITLE
ChamferDistancePytorch functions require too much memory

### ISSUE THREAD

**Issue by marcusabate** [junzhezhang/shape-inversion#3]
When trying to run `trainer` in `completion` mode, CUDA runs out of memory very quickly. I'm running this on an 8GB GPU, but CUDA is asking for over 15GB. This happens whenever calls to `distChamfer` and `distChamfer_raw` are made. 

Is there a recommended setting to run shape-inversion on smaller machines before going to a larger computer cluster? It would be great if I could train remote and then complete shapes locally even if the full evaluation isn't done in the loop, as I can always evaluate afterwards.

Thank you.

**Comment by Pikoyooo** [comment]
hi~I thought I'm facing the same problem. May I know what you do to slove it?
