### ISSUE TITLE
A naive question

### ISSUE THREAD

**Issue by duzhenjiang113** [junzhezhang/shape-inversion#4]
Hello, I have some questions about the paper. What is the input of your article during testing, is it a partial shape? And how is it encoded into a code z to generate a completed shape?

**Comment by junzhezhang** [comment]
Hi, refering to Fig. 2 in the paper, x_in is the input. We first start with an initialization stage, in which hundreds of latent vectors z are sampled randomly, and the one with minimum L is chosen for optimization, i.e., the gradient descent process in Fig. 2. Hope this clarifies.

**Comment by duzhenjiang113** [comment]
thanks
