### ISSUE TITLE
How long does it take to train?

### ISSUE THREAD

**Issue by gxwangupc** [junzhezhang/shape-inversion#5]
I feel very interested in your work. I'd like to know what GPUs you were using and how long does it take to train.

**Comment by junzhezhang** [comment]
Hi,
In the GAN Inversion stage, for each of the test example, it takes roughly half a minute on a single V100. The framework supports distributed.

For pertaining, it takes less than 10 hours on 4 V100.

**Comment by gxwangupc** [comment]
Thank you very much.
