### ISSUE TITLE
Inter-Realsense PointCloud

### ISSUE THREAD

**Issue by liu52020** [junzhezhang/shape-inversion#6]
Hello! Can your code complete the stair-type point cloud data obtained by Inter-Realsense?

**Comment by junzhezhang** [comment]
Hi, thanks for your interest in our work. Our method is invariant to the sensors and point cloud domain, as long as the category of objects has some complete shapes (synthetic and unpaired) to pretrain the GAN. Hope it clarifies.

**Comment by liu52020** [comment]
So is it understandable? When I train your code, I select CRN for dataset, chair for class_choice, and my own stair point cloud data (.pcd format) in dataset_path. I wonder if this is ok? Thank you for your answers!

**Comment by junzhezhang** [comment]
I believe you would need to modify the existing dataset class or write you own ones, as currently my dataset classes handle h5 and ply data only.

**Comment by liu52020** [comment]
Thank you for your answers and suggestions, and I wish you success in your work!
