### ISSUE TITLE
About pretrained weights

### ISSUE THREAD

**Issue by xljh0520** [junzhezhang/shape-inversion#8]
Hi, thanks for sharing your pretrained weights. I ran code with your weight and follow your step. However, I can't get the same CD loss as your paper reported.
In your paper CD loss on table is 16.2, but I got 20.8.
Is this reasonable? Thanks for your reply in advance.

**Comment by junzhezhang** [comment]
Hi,

Thanks for your interest in our work. I do expect a run-to-run variance, typically +/- 1, but such a high CD value looks abnormal. The benchmark test is conducted on the ShapeNet data prepared by the CRN paper, in which we have 150 partial shapes for each category. Is that consistent with your settings? Please share more details so that I may have a clue on the abnormality.

Thanks,
Junzhe

**Comment by xljh0520** [comment]
> Hi,
> 
> Thanks for your interest in our work. I do expect a run-to-run variance, typically +/- 1, but such a high CD value looks abnormal. The benchmark test is conducted on the ShapeNet data prepared by the CRN paper, in which we have 150 partial shapes for each category. Is that consistent with your settings? Please share more details so that I may have a clue on the abnormality.
> 
> Thanks, Junzhe

Thannks for your reply. For the dataset I used the CRN test dataset and it has 150 partial shapes. And as for the weights I used the weight you offered.
The command is 


```
python trainer.py \
--dataset CRN \
--class_choice table\
--inversion_mode completion \
--mask_type k_mask \
--save_inversion_path ./saved_results/CRN_table \
--ckpt_load pretrained_models/table.pt 

python eval_completion.py \
--eval_with_GT true \
--saved_results_path saved_results/CRN_table 
```

**Comment by xljh0520** [comment]
| CD value | Plane| Cabinet | Car | Chair | Lamp | Sofa | Table | Boat | Average|
| ---          | ---    | ---         | ---|      --- | ---   |    --- |   --- |   ---- |   ---|
| Paper report      | 5.6  | 16.1| 13.0| 15.4| _18.0_| 24.6| _16.2_| 10.1|  14.9|
| My result  |           4.3 | 18.6| 12.0| 16.2 | _14.4_| 22.6| _20.8_ | 10.1 | 14.9|

Are the results too random?

**Comment by junzhezhang** [comment]
Hi, 
I believe that the randomness in initialization do affect the results. I would suggest you to run two more times for the classes that shows a big differences, ie, Lamp and Table. 

Best,
Junzhe

**Comment by lx709** [comment]
Dear Dr. Zhang, 
      Thanks for sharing your interesting work. I'm currently working on the same task and want to compare the performance with your ShapeInversion model. Would you please share the pretrained weights? I tried to train the model but found it took a long time. Look forward to your reply.
Best,
Xiang

**Comment by junzhezhang** [comment]
Hi Xiang,

The pretrained models are provided in this repo, you can simply download and conduct the inversion(completion).

Thanks,
Junzhe
